export const armors = [

];

export const warMecas =[

];


export const weapons = [
    {name: 'FA#102.6', type:'laser rifle',assistance:false, price : 12.5, img:'FA102_6', ammo:'3.5LH', magazine: 12, range: 'long range'},
    {name: 'FA#115.7', type:'laser rifle',assistance:true, price : 12.2, img:'FA115_7', ammo:'3.7LH', magazine: 7, range: 'long range'},
    {name: 'FA#97.5', type:'laser rifle',assistance:false, price : 12.0, img:'FA97_5', ammo:'4.0LH', magazine: 4, range: 'short range'},
    {name: 'FA#142.3', type:'blaster',assistance:false, price : 12.0, img:'FA142_3', ammo:'7.4LH', magazine: 5, range: 'short range'},
    {name: 'FA#135.2', type:'blaster',assistance:false, price : 12.2, img:'FA135_2', ammo:'8LH', magazine: 5, range: 'short range'},
    {name: 'FA#135.6', type:'blaster',assistance:true, price : 12.3, img:'FA135_6', ammo:'8.5LH', magazine: 5, range: 'short range'},
    {name: 'FA#84.6', type:'blaster',assistance:false, price : 12.5, img:'FA84_6', ammo:'4.2LH', magazine: 4, range: 'short range'},
    {name: 'FA#106.3', type:'laser sniper rifle',assistance:true, price : 12.2, img:'FA106_3', ammo:'7.3LH', magazine: 6, range: 'very long range'},
    {name: 'FA#128.7', type:'laser sniper rifle',assistance:true, price : 12.3, img:'FA128_7', ammo:'7.8LH', magazine: 5, range: 'very long range'},
    {name: 'FA#144.3', type:'laser rifle',assistance:true, price : 12.2, img:'FA144_3', ammo:'4.2LH', magazine: 7, range: 'long range'},
    {name: 'FA#94.3', type:'blaster',assistance:false, price : 12.8, img:'FA94_3', ammo:'6.4LH', magazine: 4, range: 'short range'},
    {name: 'FA#128.1', type:'blaster',assistance:false, price : 12.0, img:'FA128_1', ammo:'7.2LH', magazine: 8, range: 'short range'},
    {name: 'FA#122.3', type:'blaster',assistance:false, price : 12.9, img:'FA122_3', ammo:'8.7LH', magazine: 4, range: 'short range'},
    {name: 'FA#128.3', type:'blaster',assistance:false, price : 12.5, img:'FA128_3', ammo:'7.5LH', magazine: 6, range: 'short range'},
    {name: 'FA#118.7', type:'laser rifle', assistance:true, price : 12.0, img: 'FA118_7', ammo:'4.5LH', magazine: 14, range: 'long range'},
    {name: 'WM#28.5', type:'armored', assistance:true, price : 10, img: 'WM28_5', flying: true, cockpit:2, weapons:'light'},
    {name: 'WM#28.7', type:'armored', assistance:false, price : 10, img: 'WM28_7', flying: true, cockpit:2, weapons:'solid'},
    {name: 'WM#17.9', type:'armored', assistance:false, price : 10, img: 'WM17_9', flying: false, cockpit:3, weapons:'heavy'},
    {name: 'WM#2.6', type:'armored', assistance:false, price : 10, img: 'WM2_6', flying: false, cockpit:2, weapons:'light'},
    {name: 'WM#16.2', type:'agile', assistance:true, price : 10, img: 'WM16_2', flying: false, cockpit:1, weapons:'light'},
    {name: 'WM#24.4', type:'hybrid', assistance:true, price : 10, img: 'WM24_4', flying: true, cockpit:2, weapons:'solid'},
    {name: 'WM#6.9', type:'armored', assistance:false, price : 10, img: 'WM6_9', flying: false, cockpit:3, weapons:'heavy'},
    {name: 'WM#11.3', type:'armored', assistance:true, price : 10, img: 'WM11_3', flying: false, cockpit:2, weapons:'solid'},
    {name: 'WM#3.8', type:'hybrid', assistance:true, price : 10, img: 'WM3_8', flying: true, cockpit:4, weapons:'heavy'},
    {name: 'WM#18.6', type:'armored', assistance:false, price : 10, img: 'WM18_6', flying: false, cockpit:2, weapons:'heavy'},
    {name: 'WM#1.6', type:'armored', assistance:false, price : 10, img: 'WM1_6', flying: false, cockpit:2, weapons:'heavy'},
    {name: 'WM#5.1', type:'agile', assistance:true, price : 10, img: 'WM5_1', flying: false, cockpit:1, weapons:'solid'},
    {name: 'WM#20.8', type:'hybrid', assistance:true, price : 10, img: 'WM20_8', flying: true, cockpit:2, weapons:'light'},
    {name: 'WM#12.8', type:'armored', assistance:true, price : 10, img: 'WM12_8', flying: false, cockpit:2, weapons:'solid'},
    {name: 'CA#94.9', type:'shielded', assistance:true, price: 10, img: 'CA94_9', flying:false},
    {name: 'CA#95.2', type:'shielded', assistance:true, price: 10, img: 'CA95_2', flying:false},
    {name: 'CA#63.3', type:'shielded', assistance:false, price: 10,  img: 'CA63_3', flying:false},
    {name: 'CA#101.1', type:'agile', assistance:true, price: 10, img: 'CA101_1', flying:true},
    {name: 'CA#74.6', type:'shielded', assistance:true, price: 10, img: 'CA74_6', flying:false},
    {name: 'CA#53.2', type:'agile', assistance:true, price: 10, img: 'CA53_2', flying:false},
    {name: 'CA#53.8', type:'agile', assistance:true, price: 10, img: 'CA53_8', flying:false},
    {name: 'CA#54.3', type:'agile', assistance:true, price: 10, img: 'CA54_3', flying:false},
    {name: 'CA#54.5', type:'agile', assistance:true, price: 10, img: 'CA54_5', flying:false},
    {name: 'CA#74.3', type:'shielded', assistance:true, price: 10, img: 'CA74_3', flying:false},
    {name: 'CA#75.1', type:'shielded', assistance:true, price: 10, img: 'CA75_1', flying:false},
    {name: 'CA#75.5', type:'shielded', assistance:true, price: 10, img: 'CA75_5', flying:false},
    {name: 'CA#98.4', type:'agile', assistance:false, price: 10,  img: 'CA98_4', flying:true},
    {name: 'CA#98.2', type:'agile', assistance:false, price: 10,  img: 'CA98_2', flying:true},
    {name: 'CA#98.7', type:'agile', assistance:true, price: 10, img: 'CA98_7', flying:true},
    {name: 'CA#99.2', type:'agile', assistance:true, price: 10, img: 'CA99_2', flying:true},
    {name: 'CA#99.5', type:'agile', assistance:true, price: 10, img: 'CA99_5', flying:true},
    {name: 'CA#99.6', type:'agile', assistance:true, price: 10, img: 'CA99_6', flying:true},
    {name: 'CA#10.3', type:'agile', assistance:true, price: 10, img: 'CA10_3', flying:true},
    {name: 'CA#162.7', type:'agile', assistance:true, price: 10, img: 'CA162_7', flying:true},
    {name: 'CA#162.4', type:'agile', assistance:true, price: 10,  img: 'CA162_4', flying:true},
    {name: 'CA#45.5', type:'shielded', assistance:false, price: 10,  img: 'CA45_5', flying:false},
    {name: 'CA#45.8', type:'shielded', assistance:false, price: 10,  img: 'CA45_8', flying:false},
    {name: 'CA#92.5', type:'shielded', assistance:true, price: 10, img: 'CA92_5', flying:false},
    {name: 'CA#94.3', type:'shielded', assistance:true, price: 10, img: 'CA94_3', flying:false},
    {name: 'CA#94.7', type:'shielded', assistance:true, price: 10, img: 'CA94_7', flying:false},
];